restore_npm: &restore_npm
  restore_cache:
    keys:
      - node-12-v1-npm-cache-{{ checksum "package-lock.json" }}

install_node_modules: &install_node_modules
  run: |
    npx installed-check || npm install

cache_npm: &cache_npm
  save_cache:
    key: node-12-v1-npm-cache-{{ checksum "package-lock.json" }}
    paths:
      - node_modules

version: 2.1
jobs:
  build:
    docker:
      - image: node:12-alpine
    working_directory: /extension
    steps:
      - checkout
      - *restore_npm
      - *install_node_modules
      - *cache_npm
      - run: NODE_ENV=production npx webpack
      - run: |
          mkdir -p /tmp/extension
          cp -r ./manifest.json /tmp/extension
          cp -r ./popup.html /tmp/extension
          cp -r ./dist /tmp/extension
          mkdir -p /tmp/extension/images/icons
          cp -r ./images/icons/* /tmp/extension/images/icons/
      - run: apk add --upgrade --no-cache zip
      - run: zip -rj /tmp/extension.zip /tmp/extension
      - store_artifacts:
          path: /tmp/extension.zip
workflows:
    ci:
      jobs:
        - build
